FROM node:20-alpine

WORKDIR /app

# Install dependencies
COPY package.json package-lock.json* ./
RUN npm ci

# Install dev tools
RUN npm install -g nodemon ts-node typescript

# Expose port
EXPOSE 3016

# Start server u watch modu
CMD ["nodemon", "--watch", "src", "--ext", "ts,js", "--exec", "ts-node", "src/app.ts"]